# -*- mode: ruby -*-
# vi: set ft=ruby :

$update_script = <<SCRIPT
apt update
# apt upgrade -y
apt install python3 -y
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.hostmanager.enabled = false
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.ssh.forward_agent = true
 
  config.vm.define :master do |master|
    config.vm.provider "virtualbox" do |vb|
      vb.cpus = "2"
      vb.memory = "1024"
    end
  master.vm.network :private_network, ip: "10.211.155.239"
  master.vm.hostname = "tpos-master"
  master.vm.provision :hostmanager
  master.vm.provision :shell, :inline => $update_script
  master.vm.provision :shell, inline: <<-SHELL
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    sudo service ssh restart
  SHELL
  end
 end 